### ISSUE TITLE
c++ examples?

### ISSUE THREAD

**Issue by antithing** [hovren/kontiki#5]
Hi, and thank you for this code. I would like to use it in c++ without any Python. is this possible?

What is the input data required? 

Thanks!

**Comment by hovren** [comment]
Yes it is a C++ library with python bindings, so using it from C++ works
fine.

You should be able to mostly mimic the Python examples, except for maybe a
few minor helper functions that are only implemented in the Python library.


Den sön 1 okt. 2023 10:15antithing ***@***.***> skrev:

**Comment by antithing** [comment]
Great,, thank you!
